export = {
    prefab: {
        //大厅
        main: "plaza/prefab/main",
        //----------topMain----------
        userInfoPanel: "plaza/prefab/userInfoPanel",
        vip: "plaza/prefab/vip",
        monthlyCard: "plaza/prefab/monthlyCard",
        foreverCard: "plaza/prefab/foreverCard",
        mails: "plaza/prefab/mail/mails",
        mail: "plaza/prefab/mail/mail",
        mailRewark: "plaza/prefab/mail/mailRewark",
        boxex: "plaza/prefab/boxes",
        //----------middleMain----------
        matching: "plaza/prefab/matching",
        levelBoxBG: "plaza/prefab/levelBox/levelBoxBG",
        friends: "plaza/prefab/friends/friends",
        chats: "plaza/prefab/chats/chats",
        gm: "plaza/prefab/gm/gm",
        role: "plaza/prefab/roles/role",
        roleUnlock: "plaza/prefab/roles/roleUnlock",
        //best:"plaza/prefab/changeRole",
        activity: "plaza/prefab/activity/activity",
        signIn: "plaza/prefab/signIn/signIn",
        day: "plaza/prefab/signIn/day",
        dailyTask: "plaza/prefab/dailyTask/dailyTask",
        invitingFriends: "plaza/prefab/invitingFriends",
        shop: "plaza/prefab/shop/shop",
        //----------bottomMain----------
        talentBG: "plaza/prefab/talent/talentBG",
        effects: "plaza/prefab/effects/effects",
        effect: "plaza/prefab/effects/effect",
        effectConfig: "plaza/prefab/effects/effectConfig",
        effectInfo: "plaza/prefab/effects/effectInfo",
        achievementBG: "plaza/prefab/achievement/achievementBG",
        guilds: "plaza/prefab/guild/guilds",
        guildsInfo: "plaza/prefab/guild/guildsInfo",
        ranks: "plaza/prefab/ranks/ranks",
        //----------matching----------
        loading: "plaza/prefab/loading",
        battleBox: "plaza/prefab/battleBox",
        //shop

    },

    image: {
        rolePic_0: "plaza/image/role/rolePic/rolePic_0",
        rolePic_1: "plaza/image/role/rolePic/rolePic_1",
        rolePic_2: "plaza/image/role/rolePic/rolePic_2",
        rolePic_3: "plaza/image/role/rolePic/rolePic_3",
        rolePic_4: "plaza/image/role/rolePic/rolePic_4",
        rolePic_5: "plaza/image/role/rolePic/rolePic_5",
        rolePic_6: "plaza/image/role/rolePic/rolePic_6",
        rolePic_7: "plaza/image/role/rolePic/rolePic_7",
        rolePic_8: "plaza/image/role/rolePic/rolePic_8",
        rolePic_9: "plaza/image/role/rolePic/rolePic_9",
        roleIco_0: "plaza/image/role/roleIco/roleIco_0",
        roleIco_1: "plaza/image/role/roleIco/roleIco_1",
        roleIco_2: "plaza/image/role/roleIco/roleIco_2",
        roleIco_3: "plaza/image/role/roleIco/roleIco_3",
        roleIco_4: "plaza/image/role/roleIco/roleIco_4",
        roleIco_5: "plaza/image/role/roleIco/roleIco_5",
        roleIco_6: "plaza/image/role/roleIco/roleIco_6",
        roleIco_7: "plaza/image/role/roleIco/roleIco_7",
        roleIco_8: "plaza/image/role/roleIco/roleIco_8",
        roleIco_9: "plaza/image/role/roleIco/roleIco_9",
        btn_unlock: "plaza/image/role/btn_unlock",
        //天赋
        talent_1001: "plaza/image/talent/talentIcon/talent_1001",
        talent_1002: "plaza/image/talent/talentIcon/talent_1002",
        talent_1003: "plaza/image/talent/talentIcon/talent_1003",
        talent_1004: "plaza/image/talent/talentIcon/talent_1004",
        talent_1005: "plaza/image/talent/talentIcon/talent_1005",
        talent_1006: "plaza/image/talent/talentIcon/talent_1006",
        talent_1007: "plaza/image/talent/talentIcon/talent_1007",
        talent_1008: "plaza/image/talent/talentIcon/talent_1008",
        talent_1009: "plaza/image/talent/talentIcon/talent_1009",
        talent_1010: "plaza/image/talent/talentIcon/talent_1010",
        talent_1011: "plaza/image/talent/talentIcon/talent_1011",
        talent_2001: "plaza/image/talent/talentIcon/talent_2001",
        talent_2002: "plaza/image/talent/talentIcon/talent_2002",
        talent_2003: "plaza/image/talent/talentIcon/talent_2003",
        talent_2004: "plaza/image/talent/talentIcon/talent_2004",
        talent_2005: "plaza/image/talent/talentIcon/talent_2005",
        talent_2006: "plaza/image/talent/talentIcon/talent_2006",
        talent_2007: "plaza/image/talent/talentIcon/talent_2007",
        talent_2008: "plaza/image/talent/talentIcon/talent_2008",
        talent_2009: "plaza/image/talent/talentIcon/talent_2009",
        talent_2010: "plaza/image/talent/talentIcon/talent_2010",
        talent_2011: "plaza/image/talent/talentIcon/talent_2011",
        talent_3001: "plaza/image/talent/talentIcon/talent_3001",
        talent_3002: "plaza/image/talent/talentIcon/talent_3002",
        talent_3003: "plaza/image/talent/talentIcon/talent_3003",
        talent_3004: "plaza/image/talent/talentIcon/talent_3004",
        talent_3005: "plaza/image/talent/talentIcon/talent_3005",
        talent_3006: "plaza/image/talent/talentIcon/talent_3006",
        talent_3007: "plaza/image/talent/talentIcon/talent_3007",
        talent_3008: "plaza/image/talent/talentIcon/talent_3008",
        talent_3009: "plaza/image/talent/talentIcon/talent_3009",
        talent_3010: "plaza/image/talent/talentIcon/talent_3010",
        talent_3011: "plaza/image/talent/talentIcon/talent_3011",
        //vip
        vip_0: "plaza/image/vip/vipIcon/v0",
        vip_1: "plaza/image/vip/vipIcon/v1",
        vip_2: "plaza/image/vip/vipIcon/v2",
        vip_3: "plaza/image/vip/vipIcon/v3",
        vip_4: "plaza/image/vip/vipIcon/v4",
        vip_5: "plaza/image/vip/vipIcon/v5",
        vip_6: "plaza/image/vip/vipIcon/v6",
        vip_7: "plaza/image/vip/vipIcon/v7",
        vip_8: "plaza/image/vip/vipIcon/v8",
        vip_9: "plaza/image/vip/vipIcon/v9",

        //签到
        vipIco_2: "plaza/image/signIn/vipIco_2",
        vipIco_3: "plaza/image/signIn/vipIco_3",
        vipIco_4: "plaza/image/signIn/vipIco_4",
        vipIco_5: "plaza/image/signIn/vipIco_5",
        vipIco_6: "plaza/image/signIn/vipIco_6",
        vipIco_7: "plaza/image/signIn/vipIco_7",
        vipIco_8: "plaza/image/signIn/vipIco_8",
        vipIco_9: "plaza/image/signIn/vipIco_9",
        box_3: "plaza/image/signIn/box_3",
        box_7: "plaza/image/signIn/box_7",
        box_14: "plaza/image/signIn/box_14",
        box_21: "plaza/image/signIn/box_21",
        openBox_3: "plaza/image/signIn/openBox_3",
        openBox_7: "plaza/image/signIn/openBox_7",
        openBox_14: "plaza/image/signIn/openBox_14",
        openBox_21: "plaza/image/signIn/openBox_21",

    },

    config: {

    }
};